### ISSUE TITLE
[Issue]Listening to bank logs then stealing cash doesn't work

### ISSUE THREAD

**Issue by TheOrangeGaming** [perfilrobo/hexbot#11]
When I'm stealing from the bank the script doesn't notice that it's already saved and gives me a popup saying my cracker is shit which can't be true I have a 28 cracker does anyone know a fix for this if so please help me :D

**Comment by johnyob** [comment]
I'm getting the same issue

**Comment by Hobolandjacob** [comment]
This is an error thrown by the server not the extension so this can be true.

**Comment by gresendesa** [comment]
The specified problems are already solved. Please, check it out and confirm. Thanks.
