### ISSUE TITLE
Extension not working 

### ISSUE THREAD

**Issue by madrileanu** [perfilrobo/hexbot#12]
Hello everyone,

The extension is not working anymore.
Is there a way to fix it?

Thanks.

**Comment by cmathiswausau** [comment]
What is not working with it? if your talking about that it is not able to run, you might want to check that your manifest file is correctly setup.

**Comment by perfilrobo** [comment]
Hey guys. I have to apologize. I've been offline for a long time. There are a bunch of pendent questions I did't answer them yet. Actually I'm kind of busy in work. As soon as I get it over I'll resume this project. By the way, feel free to modify the code. Just pull request me.

**Comment by gresendesa** [comment]
The specified problems are already solved. Please, check it out and confirm. Thanks.
