### ISSUE TITLE
Ack... if you dont have a Cracker

### ISSUE THREAD

**Issue by cmathiswausau** [perfilrobo/hexbot#20]
Please setup a double check for a cracker before performing mission related items, I just went through about 4 jobs and aborted them before  I realized what was happening.

Either that or disable the abort sequence.

But thank you for updating this otherwise.

**Comment by perfilrobo** [comment]
Ok. We'll work on it as soon as possible. It was added to [next goals](https://github.com/perfilrobo/hexbot/wiki/Next-goals)

**Comment by dominicusdev** [comment]
Regarding next goals, I won't be able to do the researcher properly, I'm unable to figure out a way of bypassing reCAPTCHA

**Comment by dominicusdev** [comment]
@cmathiswausau Can you please elaborate this? Like for each mission it should go check whether it can find a cracker or not?

**Comment by dominicusdev** [comment]
.. Or do you mean before even starting a new mission?

**Comment by cmathiswausau** [comment]
BasicallyI, I didn't have my cracker running at the time because I had just
upgraded it. I am guessing that the bot didn't check that there was a
cracker even in my software in the first place.

**Comment by dominicusdev** [comment]
I'll finish the bank account script and I'll take a look at that

**Comment by gresendesa** [comment]
Now the bot asks for permission to abort missions. Please, check it out and confirm. Thanks.
