### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by ProXyy44** [perfilrobo/hexbot#23]
I have a suggestion, How about a button which uploads, installs and hides a virus on every IP on your hacked database?
It would save alot of time.

Thank you :)

**Comment by gresendesa** [comment]
Sure. It can be implemented soon. A new bot implementation is in course, started the scratch: https://github.com/perfilrobo/hexbot/tree/hexbot-jSpaghetti

I guess a new module can be implemented to do that.
