### ISSUE TITLE
Upload, install and hide doesn't work

### ISSUE THREAD

**Issue by SaifA00** [perfilrobo/hexbot#32]
it goes to 1.2.3.4 everytime and installs the virus it doesn't work

**Comment by gresendesa** [comment]
Ow. Ok. I'll fix it soon

**Comment by gresendesa** [comment]
Hey, download the latest release (https://github.com/perfilrobo/hexbot/releases/tag/v0.1.13.1) and try again. Please, inform me if this is working or not.

**Comment by gresendesa** [comment]
OK. I've just found the bug. It is fixed. Download the latest version: https://github.com/perfilrobo/hexbot/releases (v0.1.13.2)

**Comment by SaifA00** [comment]
It works now but almost after each log clearing it stops and I have to refresh for it to complete

**Comment by gresendesa** [comment]
Does it always happen? It happens for me too but just once in a while. I think it's due the ocasional internet slow. When there is progress bar running, the bot does nothing. It just waits for page to reload. Anyway once it happens again, check the browser console, copy and paste the jSpaghetti logs here.
