### ISSUE TITLE
Add ability to multitask

### ISSUE THREAD

**Issue by RhapsodySL** [perfilrobo/hexbot#33]
Specifically, it would be nice to add a feature to check for jobs every five minutes (like it currently does), and if a job comes up while it's doing some other task (like uploading viruses to certain IPs), it should do the missions, and then go back to uploading viruses.

Of course, it should prioritize uploading, running, and hiding above all of that so it doesn't leave a virus partially installed.

**Comment by gresendesa** [comment]
It's implemented. Check it out.
