### ISSUE TITLE
Allow user to specify the minimum internet speed to upload on when uploading viruses automatically

### ISSUE THREAD

**Issue by RhapsodySL** [perfilrobo/hexbot#34]
In some cases, you'll find a lot of people with very slow internet speeds on their machine, and if you're automatically uploading viruses to them, it could take a long while, especially if the virus in question is big. Allow the user to specify the minimum internet speed when uploading a virus, and make the bot skip over any IPs that don't meet that minimum.

**Comment by gresendesa** [comment]
Ok. It's implemented. Check out the latest version: https://github.com/perfilrobo/hexbot/releases
