### ISSUE TITLE
Wrap web crawler into auto-upload

### ISSUE THREAD

**Issue by RhapsodySL** [perfilrobo/hexbot#35]
...the general idea being that you can go through IPs while auto-uploading, and the bot would scrape all of the IPs and add them to the list of IPs to automatically upload to (provided it's not already on the list). Ideally, the bot would also collect information the web crawler normally would in this state.

In essence, this combines the two features to allow the bot to keep uploading nearly indefinitely until it reaches a dead end.

**Comment by gresendesa** [comment]
Suggestion implemented. Check the latest version out.
