### ISSUE TITLE
Prevent the BOT box from popping up on most new pages that aren't running the bot currently

### ISSUE THREAD

**Issue by RhapsodySL** [perfilrobo/hexbot#36]
When you open a new page, like the Log File, while you aren't using the bot, the BOT box will pop up, requiring you to close it. This happens often enough to be very annoying. Ideally, this box should only pop up when the user presses on the button.

Another thing that's relevant, when the window isn't taking up the entire screen (if it's snapped to one half of the screen, for example), the button to close the box disappears.

**Comment by gresendesa** [comment]
Well, this behavior is defined purposely. It's make the process more intuitive for new users. But you can 
customize this behavior by yourself. Just go to libraries/classes/Bot.js and set **isHidden** as true. Next reload the extension.

I'll fix the close button problem soon.
