### ISSUE TITLE
Optionally transfer the money to one of your bank accounts during Check Amount missions

### ISSUE THREAD

**Issue by RhapsodySL** [perfilrobo/hexbot#37]
When doing Check Amount missions, you can transfer money to your own bank account without any penalty, besides Safenet potentially tracking you.

**Comment by gresendesa** [comment]
Check your previous requests out and give your feedback before doing other requests. Thanks.

**Comment by RhapsodySL** [comment]
I don't see what feedback there is to give other than saying 'thank you'. The feature is implemented; if I had any comments about it's implementation I would've done it when I made the issue.

**Comment by gresendesa** [comment]
Implemented. Check it out.
