### ISSUE TITLE
bot stops doing missions (console log and error attached)

### ISSUE THREAD

**Issue by SaifA00** [perfilrobo/hexbot#41]
**# the bot stops doing missions after it go to a mission that someone had taken**
![capture](https://cloud.githubusercontent.com/assets/19435635/15447608/72126498-1f59-11e6-8fdc-03bc6816e41c.JPG)

**# Here is a picture of the console**
![console](https://cloud.githubusercontent.com/assets/19435635/15447614/8e35cb1a-1f59-11e6-871b-67326d42f98c.JPG)

**# and here is the error in line 133**
![line133](https://cloud.githubusercontent.com/assets/19435635/15447617/9bcee1a8-1f59-11e6-9309-6c7548a1b1a9.JPG)

**# I think you should edit it to repeat the process of finding mission if it cannot click**

**Comment by perfilrobo** [comment]
Ok. Thanks for the detailed report. I'm working on it.

**Comment by SaifA00** [comment]
Can you tell me when would you finish approximately??

**Comment by perfilrobo** [comment]
today

**Comment by perfilrobo** [comment]
I've just merged the changes @gresendesa has made

**Comment by SaifA00** [comment]
Ok, it works well now.
Thank you
