### ISSUE TITLE
The bot does not complete mission in bank transfer missions.

### ISSUE THREAD

**Issue by SaifA00** [perfilrobo/hexbot#44]
# the bot stops at this page and does nothing
![bug](https://cloud.githubusercontent.com/assets/19435635/15656506/23d310fe-26b9-11e6-8a08-ceefe672cf51.PNG)

# This is the console
![console](https://cloud.githubusercontent.com/assets/19435635/15656489/d953575a-26b8-11e6-9ea1-a555941207bb.PNG)
# note:This problem is happening after the last update

**Comment by gresendesa** [comment]
Does it always happen or just once?

**Comment by SaifA00** [comment]
Always

**Comment by gresendesa** [comment]
Fixed

**Comment by SaifA00** [comment]
It works well now, but I don't like the new update that accepts medium missions I think it's better to choose between type of missions not difficulty
