### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Huskyunion** [perfilrobo/hexbot#50]
I use a virus that is 700 MB. I normally leave it to infect a large list while I do stuff irl. and I dont want to waste 1 hour on 1 server that will never make any money. I suggest the ability to not upload a virus to a server on 1mb/4mb servers.

**Comment by perfilrobo** [comment]
Have you ever tried to use time limit?
You can ignore servers that will take too much time.
Just specify the time limit in seconds.

**Comment by Huskyunion** [comment]
@perfilrobo Oh its a time limit, it said wait until so I thought it'd wait 10 minutes on 1 host. thanks.
