### ISSUE TITLE
One suggestion.

### ISSUE THREAD

**Issue by QuesoConMantequilla** [perfilrobo/hexbot#53]
Is it possible to insert a specific bank account with his IP (Talking about the BANK IP), transfer the money to your account and instantly make it be BTC?
It should be useful for people looking for bank accounts and dont getting risk to get stealed..

**Comment by perfilrobo** [comment]
Hi. Have you ever tried to check the "Transfer the earned money to connected BTC wallet" option? It does exactly what you are saying.

Note: This option is only available since the [penultimate version](https://github.com/perfilrobo/hexbot/releases/tag/v0.1.21).

**Comment by QuesoConMantequilla** [comment]
No no, im talking about something like this:
Ip 659.693.495 recollected his money from viruses and ip 330.500.0.0 got his bank account.
Ip 330 goes to that bank, cracks bank account and logs in, before he can delete the logs he gets all his money stealed.
So, the bot option should be:
IP 659 recollects money, IP 330 uses the bot and inserts the bank account, the bot automatically does the progress like the 2do option (cant remember the game) and automatically transfers it to BTC.
If you want more explanations, tell me.

**Comment by perfilrobo** [comment]
Got it. I'll try to implement your suggestion soon.

**Comment by QuesoConMantequilla** [comment]
I got other ideas, after im going to create a thread with these ideas.
Thanks! Closing thread.
