### ISSUE TITLE
Some suggests for the BOT

### ISSUE THREAD

**Issue by Protorne** [perfilrobo/hexbot#55]
When the BOT does the mission, the way it does is like this: Hack the account ==> Log in the account ==> transfer the money ==> log out from the account ==> log in again to the bank to erase the log... it's not convenient.... Imagine, people always wait in the bank's log and keep refreshing them to get informations so that sometimes you may not have enough time to do like this... 
Which means the way it works is not secure enough to cover the track... i suggest this way:
1: Hack bank account ==> Log in the account (Leave the Account Overview tab there)
2: Log in the bank ==> (back to A.O tab) Transfer money :) ==> Back to the Log tab to delete log
3: Log out and get to another bank to delete logs if necessary.
4: Delete your log and finish the mission :)
This way will shorten some page loading which will helps some low-connection internet guys in real-life.
P/s: I have to say that I admire your work on this and to represent for all players using this, I want to say THANK YOU and GOOD JOB !!! :D
Thanks for reading all of this :) Hope to hear good news from you soon :)
You can email me in the game with this username: Spencer Destroy

**Comment by perfilrobo** [comment]
@Protorne Thank you very much for your words. :)

Yes! I will try to implement your suggestion. Yes I agree with the fact that the missions sequences are kinda unsafe. I must improve it.
