### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by WolfGFX** [perfilrobo/hexbot#67]
Alright, so i been here 'long time, you might remember me as MentalMushroom.
I have taken a break off for a couple of months, and am blown away by this github project.
The feedback is UNREAL. Anyways, back to the suggestion.
My suggestion is that, if it is possible, that you could implement a "Self Upgrading Software" Part to the bot.
Here is what i mean, 
You go to your software, and decide to upgrade it by 0.1, right?
You dont want to waste time upgrading the software, so. The bot, when on the "upgrade" Page, click on the software upgrade button, and boom. Everything is complete. You then just fill out the Captcha and that is 30 Seconds Saved from the normal time.

If this is possible, i would suggest a even more difficult option.
When in any page of hacker experience, click the "Upgrade Software" Button, Select the software you want to upgrade, and select what version you want to upgrade it to. Say for example...
Upgrade my 2.8 Cracker to 5.0. Then, the bot will automatically do the captcha's, and once the upgrade is done, it will do it again, so that it is a kind of... "AFK Upgrader Bot" Type of thing.
This would be EXTREMELY Useful for people who dont have much time to play this game and want to get as far as they can.

This is a challenge i would highly suggest trying out. 
Thanks,
Wolf. (MentalMushroom)

( I have already said this is my MentalMushroom Account, i just didnt do it in full detail. And i believe that with the advance of over 3 Months, this should be possible in some sort of way. )

**Comment by dominicusdev** [comment]
This exact thing has been discussed multiple times, I even were doing one back when I was active.
The thing is; the captcha's are really hard to bypass nowadays, so this is not an option at this stage. :/

**Comment by WolfGFX** [comment]
Closed.

**Comment by WolfGFX** [comment]
Closed.
