### ISSUE TITLE
botao de fechar nao aparece

### ISSUE THREAD

**Issue by lok2** [perfilrobo/hexbot#72]
olha já tentei de todas as formas, ja reinstalei a extensao, limpei o cache já até resetei meu ip, gostaria de saber como resolver o botao de fechar nao aparece mais, estava normal até ontem e hoje simplesmente sumiu, eu usava a versao 1.22.2 já atualizei pra versao mais recente mas sem resultado...gosto muito do bot e ajuda bastante parabens pelo script

**Comment by lok2** [comment]
antes eke ficava assim só quando eu entrava no en.hackerexperience.com, mas agora esta assim com o host br tambem

**Comment by gresendesa** [comment]
Cara, esqueci de arrumar isso. Droga. Na próxima versão já vai estar resolvido.
Mas até lá você pode resolver indo até o arquivo core/views.js e remover todas as ocorrências de "hide1024" (sem as aspas). Sacou? Vê se resolve. Depois fala aí o que aconteceu.

Everyone who are facing problems with the close button, please go to the file core/views.js and remove every occurrence of "hide1024". It will be fixed in the next version. For while just do that.

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
cara, removi todos os "hide 1024" (sem as aspas) que encontrei mas nao resolveu, continua ainda oculto

**Comment by lok2** [comment]
obrigado cara, me ajudou bastante... proxima versao se conseguirem fazer com que o bot nao trave na mensagem "are you sure" quando vc roda webcrawler com reset ip na task ajudaria muito

**Comment by gresendesa** [comment]
Vê a nova versão ae
https://github.com/perfilrobo/hexbot/releases/tag/v0.1.24.1
