### ISSUE TITLE
[Issue] Lisen transfer and upload install and hide doesn't work 

### ISSUE THREAD

**Issue by LaGallinaTuruleta** [perfilrobo/hexbot#8]
Hello,
The scripts for the missions work pretty well.
But in the "Listen transfer bank logs on " and "Upload, install and hide this " don't work for me i explain what i'm trying to do.

On "Listen transfer bank logs on" , i type "Bank IP" and and on the next field "MyAccountNumber"
Then it go to the Bank IP and try directly to hack the bank error "This ip is already on your hacked database" and a script error says "Came on man,  Your cracker is a shit" .

On "Upload, install and hide this " , it automatically choose on software field this "Advanced Warez.vwarez, 5.0" and on ip field i type "X.X.X.X ,X.X.X.X". Then it goes to anywhere and HE makes this error "Error! The IP address request.ip.pop() is invalid." then a loop begin that's imposible to stop, i have to disable the extension to stop it.

I want to know if i'm writing something bad or is it the script, i'll like to improve this script :P.
I know the basics of JavaScript.
Thanks.

**Comment by ShinXPixell** [comment]
The bot stops after cracking bank accounts in Missions for me

**Comment by MentalMushrooms** [comment]
I dont know how to install it, im on chrome (Google) But idk how to install.
I got the zip file but idk what to do with that.
Someone help me.

**Comment by gresendesa** [comment]
The especified problems are already solved. Please, check it out and confirm. Thanks.
