### ISSUE TITLE
[Issue]Missions just stop

### ISSUE THREAD

**Issue by ShinXPixell** [perfilrobo/hexbot#9]
The bot start searching for a Mission and after it finds one the bot goes to the bank IP(Check account status Missions) and begin to hack the account after it is done the bot just stops, it does the same with the transfer money missions, the problem seems to be with logging in the hacked accounts I clicked login manualy to go into accounts and from there it finished the mission on its own.

**Comment by ShinXPixell** [comment]
Edit: The check bank status work fine, the problem was not having my own account at the bank that the bot was using to crack an account, the transfer money mission works fine aswell till the end but them do not finish up the mission for me, it just stops after clearing up the logs at the bank without completing the mission and trying to get a new one

**Comment by LaGallinaTuruleta** [comment]
It happens sometimes just logout the server and it finish.

**Comment by MentalMushrooms** [comment]
I dont know how to install it, im on chrome (Google) But idk how to install.
I got the zip file but idk what to do with that.
Someone help me.

**Comment by gresendesa** [comment]
The specified problems are already solved. Please, check it out and confirm. Thanks.
